language: c

sudo: false

# DEADWOOD: prefer to use the vendored libkqueue
#addons:
#  apt:
#    packages:
#    - libkqueue0
#    - libkqueue-dev

cache:
  directories:
    - vendor/libkqueue-2.0.3

script:
- ./configure
- make
- make check
